from __future__ import annotations


OFFICIAL_VIEW_COLUMNS: dict[str, set[str]] = {
    "dbo.VwFacturaConImpuesto": {
        "Sucursal",
        "Fecha",
        "FechaDocumento",
        "HoraDocumento",
        "Trn",
        "Numero",
        "Referencia",
        "CodBarras",
        "NombreTallaColor",
        "Coleccion",
        "Coleccion_EN",
        "CodDescripTipoPrenda",
        "DescripTipoPrenda",
        "CodDescLinea",
        "Linea",
        "Descripcion3Tabla4",
        "CodDescSubLinea",
        "DescSubLinea",
        "CodColor",
        "Sublinea_EN",
        "CodEmbarque",
        "CodEmbarqueAbreviado",
        "EMB",
        "EMB_EN",
        "Talla",
        "Tabla9_Description",
        "ColorSF",
        "Color",
        "DescripcionArticulo",
        "Unidades",
        "Costo",
        "CostoTotal",
        "PrecioUnit",
        "VentaBruta",
        "Descuento",
        "DescuentoPct",
        "DescuentoValor",
        "Impuesto",
        "VentaNetaQ",
        "IdVendedor",
        "Vendedor",
        "Cuenta",
        "Cliente",
        "Direccion",
        "eMail",
        "Fecha Nacimiento",
        "Telefono",
        "Celular",
    },
    "dbo.VwExistencia": {
        "Sucursal",
        "Referencia",
        "CodBarras",
        "NombreTallaColor",
        "Coleccion",
        "Coleccion_EN",
        "CodDescripTipoPrenda",
        "DescripTipoPrenda",
        "CodDescLinea",
        "Linea",
        "CodDescSubLinea",
        "DescSubLinea",
        "CodColor",
        "Sublinea_EN",
        "CodEmbarque",
        "CodEmbarqueAbreviado",
        "Talla",
        "Tabla9_Description",
        "ColorSF",
        "Color",
        "DescripcionArticulo",
        "ExistenciaFisica",
        "ExistenciaDisponible",
        "FechaEntradaReferencia",
        "FechaEntradaEmbarque",
        "TVida",
        "idArticulo",
        "idSucursal",
    },
    "dbo.VwEntradasInventario": {
        "FechaEntrada",
        "FechaHoraEntrada",
        "Sucursal",
        "idArticulo",
        "NombreTallaColor",
        "Referencia",
        "CodBarras",
        "CodEmbarque",
        "CodEmbarqueAbreviado",
        "Linea",
        "DescripTipoPrenda",
        "Talla",
        "Color",
        "DescripcionArticulo",
        "Transaccion",
        "SiglaTransaccion",
        "UnidadesEntrada",
    },
    "dbo.VwClienteResumenCRM": {
        "NumeroCliente",
        "NitDpi",
        "Cliente",
        "Telefono",
        "Celular",
        "Email",
        "FechaUltimaCompra",
        "DiasSinCompra",
        "SegmentoSinCompra",
        "SucursalPreferida",
        "FacturasSucursalPreferida",
        "SucursalUltimaCompra",
        "NumeroUltimaFactura",
        "IdVendedorUltimaFactura",
        "VendedorUltimaFactura",
        "FacturasTotales",
        "UnidadesTotales",
        "VentaNetaTotal",
        "UnidadesFullPrecio",
        "UnidadesPromocion",
        "VentaFullPrecio",
        "VentaPromocion",
        "PorcentajeFullPrecio",
        "PorcentajePromocion",
    },
}


def required_columns(view_name: str) -> set[str]:
    return OFFICIAL_VIEW_COLUMNS.get(view_name, set())
